name: timeliner

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^5.6.0
  google_fonts: ^2.0.0
  auto_size_text: ^2.1.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  meta: ^1.3.0
  badges: ^1.2.0
  timeline_widget: ^1.0.6
  shared_preferences: ^2.0.5
  sign_button: ^1.0.2
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  google_sign_in: ^5.0.1
  cloud_firestore: ^1.0.4
  firebase_database: ^6.1.2
  share: ^2.0.1
  graphql: ^4.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true